package uit.j2ee.been;
// Generated May 30, 2017 11:41:13 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private Integer id;
     private int staffId;
     private Integer customerId;
     private Date time;
     private long subtotal;
     private int shopId;
     private int deviceId;

    public Bill() {
    }

	
    public Bill(int staffId, Date time, long subtotal, int shopId, int deviceId) {
        this.staffId = staffId;
        this.time = time;
        this.subtotal = subtotal;
        this.shopId = shopId;
        this.deviceId = deviceId;
    }
    public Bill(int staffId, Integer customerId, Date time, long subtotal, int shopId, int deviceId) {
       this.staffId = staffId;
       this.customerId = customerId;
       this.time = time;
       this.subtotal = subtotal;
       this.shopId = shopId;
       this.deviceId = deviceId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(int staffId) {
        this.staffId = staffId;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(long subtotal) {
        this.subtotal = subtotal;
    }
    public int getShopId() {
        return this.shopId;
    }
    
    public void setShopId(int shopId) {
        this.shopId = shopId;
    }
    public int getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(int deviceId) {
        this.deviceId = deviceId;
    }




}


