package uit.j2ee.been;
// Generated May 30, 2017 11:41:13 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaymentHistory generated by hbm2java
 */
public class PaymentHistory  implements java.io.Serializable {


     private Integer id;
     private int fromUserId;
     private int toUserId;
     private BigDecimal subtotal;
     private String detail;

    public PaymentHistory() {
    }

	
    public PaymentHistory(int fromUserId, int toUserId, BigDecimal subtotal) {
        this.fromUserId = fromUserId;
        this.toUserId = toUserId;
        this.subtotal = subtotal;
    }
    public PaymentHistory(int fromUserId, int toUserId, BigDecimal subtotal, String detail) {
       this.fromUserId = fromUserId;
       this.toUserId = toUserId;
       this.subtotal = subtotal;
       this.detail = detail;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFromUserId() {
        return this.fromUserId;
    }
    
    public void setFromUserId(int fromUserId) {
        this.fromUserId = fromUserId;
    }
    public int getToUserId() {
        return this.toUserId;
    }
    
    public void setToUserId(int toUserId) {
        this.toUserId = toUserId;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }




}


